[book]
authors = ["abeRodz"]
language = "en"
multilingual = true
src = "src"
title = "Vision Transformers"



[output.html]
mathjax-support = true
default-theme = "dark"
preferred-dark-theme = "ayu"
site-url = "/"
cname = ""
additional-css = ["./theme/logo.css"]
additional-js = ["./theme/logo.js"]

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0